spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${NOTIFICATION_MYSQL_HOST}:${NOTIFICATION_DB_PORT}/${NOTIFICATION_DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${NOTIFICATION_MYSQL_USERNAME}
    password: ${NOTIFICATION_MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: ${NOTIFICATION_DEV_SHOW_SQL}
