spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${AUTH_MYSQL_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${AUTH_MYSQL_USERNAME}
    password: ${AUTH_MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: ${AUTH_PROD_SHOW_SQL}
