spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${VOLUNTEER_MYSQL_HOST}:${VOLUNTEER_DB_PORT}/${VOLUNTEER_DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${VOLUNTEER_MYSQL_USERNAME}
    password: ${VOLUNTEER_MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: ${VOLUNTEER_PROD_SHOW_SQL}
